/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CDADDRESS } from './cDADDRESS';
import { CountryType } from './countryType';
import { IDKMEHR } from './iDKMEHR';
import { TextType } from './textType';


export interface AddressType {
    cds?: Array<CDADDRESS>;
    city?: string;
    country?: CountryType;
    district?: string;
    housenumber?: string;
    ids?: Array<IDKMEHR>;
    nis?: string;
    postboxnumber?: string;
    street?: string;
    texts?: Array<TextType>;
    zip?: string;
}
