/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CDERROR {
    dn?: string;
    l?: string;
    s?: CDERROR.SEnum;
    sl?: string;
    sv?: string;
    value?: string;
}
export namespace CDERROR {
    export type SEnum = 'CD_ERROR' | 'LOCAL';
    export const SEnum = {
        CDERROR: 'CD_ERROR' as SEnum,
        LOCAL: 'LOCAL' as SEnum
    }
}
