/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorWithPatientDto } from './authorWithPatientDto';
import { CDCONSENT } from './cDCONSENT';
import { KmehrPatientDto } from './kmehrPatientDto';


export interface ConsentTypeDto {
    author?: AuthorWithPatientDto;
    cds?: Array<CDCONSENT>;
    patient?: KmehrPatientDto;
    revokedate?: number;
    signdate?: number;
}
