/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConsentTypeDto } from './consentTypeDto';
import { ErrorDto } from './errorDto';


export interface ConsentMessageDto {
    complete?: boolean;
    consent?: ConsentTypeDto;
    errors?: Array<ErrorDto>;
}
