/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DmgAcknowledge {
    complete?: boolean;
    date?: Date;
    errors?: Array<Error>;
    io?: string;
    major?: string;
    message?: string;
    minor?: string;
    reference?: string;
    valueHash?: string;
}
