/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HcpartyType } from './hcpartyType';


export interface DmgConsultation {
    birthday?: number;
    complete?: boolean;
    deceased?: number;
    errors?: Array<Error>;
    firstName?: string;
    from?: number;
    hcParty?: HcpartyType;
    inss?: string;
    io?: string;
    lastName?: string;
    mutuality?: string;
    payment?: boolean;
    reference?: string;
    regNrWithMut?: string;
    sex?: string;
    to?: number;
    valueHash?: string;
}
