/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HcpartyType } from './hcpartyType';


export interface DmgNotification {
    complete?: boolean;
    errors?: Array<Error>;
    from?: Date;
    hcParty?: HcpartyType;
    io?: string;
    payment?: boolean;
    reference?: string;
    valueHash?: string;
}
