/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EattestCardReading } from './eattestCardReading';
import { EattestHcParty } from './eattestHcParty';
import { EattestRequestor } from './eattestRequestor';


export interface EattestCode {
    cardReading?: EattestCardReading;
    date?: number;
    doctorSupplement?: number;
    fee?: number;
    gmdManager?: EattestHcParty;
    internship?: EattestHcParty;
    location?: EattestHcParty;
    norm?: number;
    quantity?: number;
    reglementarySupplement?: number;
    reimbursement?: number;
    relativeService?: string;
    requestor?: EattestRequestor;
    riziv?: string;
}
