/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EattestHcParty {
    cdHcParty?: string;
    firstName?: string;
    idHcParty?: string;
    idSsin?: string;
    lastName?: string;
}
