/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Message } from './message';
import { TAck } from './tAck';


export interface EfactMessage {
    detail?: string;
    id?: string;
    message?: Message;
    name?: string;
    tack?: TAck;
    xades?: string;
}
