/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RecordRecordOrSegmentDescription } from './recordRecordOrSegmentDescription';


export interface ErrorDetail {
    creationDate?: number;
    errorCodeComment?: string;
    index?: number;
    invoicingYearMonth?: number;
    mutualityCode?: number;
    oaResult?: string;
    record?: RecordRecordOrSegmentDescription;
    rejectionCode1?: string;
    rejectionCode2?: string;
    rejectionCode3?: string;
    rejectionDescr1?: string;
    rejectionDescr2?: string;
    rejectionDescr3?: string;
    rejectionLetter1?: string;
    rejectionLetter2?: string;
    rejectionLetter3?: string;
    rejectionZoneDescr1?: string;
    rejectionZoneDescr2?: string;
    rejectionZoneDescr3?: string;
    reserve?: string;
    sendingId?: number;
}
