/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CDERROR } from './cDERROR';
import { IDKMEHR } from './iDKMEHR';
import { TextType } from './textType';


export interface ErrorType {
    cds?: Array<CDERROR>;
    description?: TextType;
    ids?: Array<IDKMEHR>;
    url?: string;
}
