/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { KmehrCd } from './kmehrCd';
import { KmehrId } from './kmehrId';


export interface HcPartyDto {
    applicationID?: string;
    cbe?: string;
    cds?: Array<KmehrCd>;
    ehp?: string;
    familyname?: string;
    firstname?: string;
    hubId?: string;
    ids?: Array<KmehrId>;
    inss?: string;
    name?: string;
    nihii?: string;
    type?: string;
}
