/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressType } from './addressType';
import { CDHCPARTY } from './cDHCPARTY';
import { IDHCPARTY } from './iDHCPARTY';
import { TelecomType } from './telecomType';


export interface HcpartyType {
    addresses?: Array<AddressType>;
    cds?: Array<CDHCPARTY>;
    familyname?: string;
    firstname?: string;
    ids?: Array<IDHCPARTY>;
    name?: string;
    telecoms?: Array<TelecomType>;
}
