/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HospitalizedInfoDto } from './hospitalizedInfoDto';
import { InsurabilityItemDto } from './insurabilityItemDto';
import { MedicalHouseInfoDto } from './medicalHouseInfoDto';


export interface InsurabilityInfoDto {
    dateOfBirth?: number;
    deceased?: number;
    faultCode?: string;
    faultMessage?: string;
    faultSource?: string;
    firstName?: string;
    generalSituation?: string;
    hospitalizedInfo?: HospitalizedInfoDto;
    inss?: string;
    insurabilities?: Array<InsurabilityItemDto>;
    lastName?: string;
    medicalHouseInfo?: MedicalHouseInfoDto;
    paymentByIo?: boolean;
    sex?: string;
    specialSocialCategory?: boolean;
}
