/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface InvoiceReceipt {
    contactPersonFirstName?: string;
    contactPersonLastName?: string;
    contactPersonPhone?: string;
    instructionsVersion?: number;
    invoiceCreationDate?: number;
    invoiceReference?: string;
    invoiceType?: number;
    invoicingType?: number;
    invoicingYearMonth?: number;
    reserve?: string;
    sendNumber?: number;
}
