/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IDPATIENT } from './iDPATIENT';


export interface KmehrPatientDto {
    eidCardNumber?: string;
    firstName?: string;
    ids?: Array<IDPATIENT>;
    inss?: string;
    isiCardNumber?: string;
    lastName?: string;
    middleName?: string;
    mutuality?: string;
    name?: string;
    regNrWithMut?: string;
    sisCardNumber?: string;
}
