/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MycarenetError {
    code?: string;
    locFr?: string;
    locNl?: string;
    msgFr?: string;
    msgNl?: string;
    path?: string;
    regex?: string;
    uid?: string;
    value?: string;
}
