/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HealthcareParty } from './healthcareParty';
import { Medication } from './medication';
import { Patient } from './patient';


export interface PrescriptionRequest {
    deliveryDate?: number;
    executorId?: string;
    feedback?: boolean;
    hcp?: HealthcareParty;
    medications?: Array<Medication>;
    notification?: string;
    patient?: Patient;
    prescriptionType?: string;
}
