/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Receipt95 {
    accountARequestedAmount?: number;
    accountARequestedAmountSign?: string;
    accountBRequestedAmount?: number;
    accountBRequestedAmountSign?: string;
    accountsABTotalRequestedAmount?: number;
    accountsABTotalRequestedAmountSign?: string;
    invoiceRecapNumber?: number;
    mutualityCode?: number;
    mutualityControlNumber?: number;
    recordsAmount?: number;
    reserve?: string;
    type?: number;
}
