/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Segment300ErrorDescription } from './segment300ErrorDescription';
import { Zone } from './zone';


export interface RecordSegment300ErrorDescription {
    description?: Segment300ErrorDescription;
    zones?: Array<Zone>;
}
