/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RecordOrSegmentDescription } from './recordOrSegmentDescription';
import { Zone } from './zone';


export interface RecordRecordOrSegmentDescription {
    description?: RecordOrSegmentDescription;
    zones?: Array<Zone>;
}
