/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdministrationQuantity } from './administrationQuantity';
import { Code } from './code';
import { Weekday } from './weekday';


export interface RegimenItem {
    administratedQuantity?: AdministrationQuantity;
    date?: number;
    dayNumber?: number;
    dayPeriod?: Code;
    timeOfDay?: number;
    weekday?: Weekday;
}
