/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MycarenetError } from './mycarenetError';
import { Payment } from './payment';


export interface TarificationConsultationResult {
    birthdate?: Date;
    codes?: Array<string>;
    ct1?: string;
    ct2?: string;
    date?: Date;
    deceased?: Date;
    errors?: Array<MycarenetError>;
    fees?: Array<Payment>;
    financialContracts?: Array<string>;
    firstName?: string;
    insurancePeriodEnd?: Date;
    insurancePeriodStart?: Date;
    justification?: number;
    lastName?: string;
    niss?: string;
    patientFees?: Array<Payment>;
    reimbursements?: Array<Payment>;
    sex?: TarificationConsultationResult.SexEnum;
}
export namespace TarificationConsultationResult {
    export type SexEnum = 'MALE' | 'FEMALE';
    export const SexEnum = {
        MALE: 'MALE' as SexEnum,
        FEMALE: 'FEMALE' as SexEnum
    }
}
