/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HcParty } from './hcParty';
import { Patient } from './patient';


export interface TherapeuticLink {
    comment?: string;
    endDate?: string;
    hcParty?: HcParty;
    patient?: Patient;
    startDate?: string;
    status?: TherapeuticLink.StatusEnum;
    type?: string;
}
export namespace TherapeuticLink {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE' | 'ALL';
    export const StatusEnum = {
        ACTIVE: 'ACTIVE' as StatusEnum,
        INACTIVE: 'INACTIVE' as StatusEnum,
        ALL: 'ALL' as StatusEnum
    }
}
